- id: '1723905215773'
  alias: Irrigazione Pomodori Avvio
  description: Avvia l'irrigazione dei pomodori basandosi sull'integrazione per la
    smart irrigation
  trigger:
  - platform: event
    event_type: smart_irrigation_start_irrigation_all_zones
  condition:
  - condition: numeric_state
    entity_id: sensor.smart_irrigation_pomodori
    above: 0
  action:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.valve_1
  - action: timer.start
    metadata: {}
    data:
      duration: '{{states(''sensor.smart_irrigation_pomodori'')}}'
    target:
      entity_id: timer.timer_1
  - action: notify.send_message
    metadata: {}
    data:
      message: Avvio irrigazione Pomodori per {{states('sensor.smart_irrigation_pomodori')}}
        secondi
  mode: single
- id: '1723905612733'
  alias: Irrigazione Pomodori Fine
  description: Attende che il timer per l'irrigazione scada per chiudere la valvola
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_1
  condition: []
  action:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.valve_1
  - action: smart_irrigation.reset_bucket
    target:
      entity_id: sensor.smart_irrigation_pomodori
    data: {}
  mode: single